# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "helloworld_centos73_virtualbox"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: "yum update -y"
  config.vm.provision "shell", path: "scripts/01-setup-r10k.sh", name: "configure r10k"
  config.vm.provision "file", source: "Puppetfile", destination: "Puppetfile"
  config.vm.provision "shell", path: "scripts/03-deploy-modules.sh", name: "deploy modules", privileged: false
  config.vm.provision "file", source: "site.pp", destination: "site.pp"

  config.vm.provision "puppet" do |p| 
    p.manifest_file = "site.pp"
    p.manifests_path = "./"
    p.working_directory = "/home/vagrant"
    p.options = "-v --modulepath=/home/vagrant/modules"
  end 

end
